apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/post"