version: '3.8'

services:
  pg_user:
    container_name: pg_user
    image: postgres
    restart: always
    env_file:
      - docker_user_db.env
    ports: ['5432:5432']
    volumes:
      - pg_user:/var/lib/postgresql/data

  pg_post:
    container_name: pg_post
    image: postgres
    restart: always
    env_file:
      - docker_post_db.env
    ports: ['5433:5432']
    volumes:
      - pg_post:/var/lib/postgresql/data

  pgadmin-compose:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@epam.com"
      PGADMIN_DEFAULT_PASSWORD: "epam"
    ports:
      - "15432:80"
    depends_on:
      - pg_user
      - pg_post

  user-service-svc:
    container_name: user-service-svc
    image: epamshorasulshoazimov/user-service:1.0.0
    restart: on-failure
    env_file:
      - docker_user_app.env
    depends_on:
      - pg_user
    ports:
      - '0.0.0.0:8091:8091'

  post-service-svc:
    container_name: post-service-svc
    image: epamshorasulshoazimov/post-service:1.0.0
    restart: on-failure
    env_file:
      - docker_post_app.env
    depends_on:
      - pg_post
    ports:
      - '0.0.0.0:8081:8081'

volumes:
  pg_post:
    driver: local
  pg_user:
    driver: local
#
#networks:
#  my_network:
#    external: true