version: '3.8'

services:


  pg_user:
    container_name: pg_user
    image: postgres
    restart: always
    env_file:
      - docker_user_db.env
    ports:
      - "0.0.0.0:54321:5432"
    volumes:
      - pg_user:/var/lib/postgresql/data

  pg_post:
    container_name: pg_post
    image: postgres
    restart: always
    env_file:
      - docker_post_db.env
    ports:
      - "0.0.0.0:54320:5432"
    volumes:
      - pg_post:/var/lib/postgresql/data

  pgadmin-compose:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@epam.com"
      PGADMIN_DEFAULT_PASSWORD: "epam"
    ports:
      - "15432:80"
    depends_on:
      - post_db
      - user_db

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: 'rabbitmq'
#    ports:
#      - 5672:5672
#      - 15672:15672
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  user-service:
    container_name: user_service
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_user:5432/user_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - pg_user
    ports:
      - '0.0.0.0:8091:8091'

  post-service:
    container_name: post_service
    build:
      context: ./post-service/
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_post:5433/post_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - pg_post
    ports:
      - '0.0.0.0:8081:8081'

volumes:
  pg_post:
    driver: local
  pg_user:
    driver: local
