apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-psql-vol-claim
  labels:
    app: user-psql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi