apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    istio-injection: enabled
    app: postgresql
spec:
  selector:
    app: postgresql
  type: ClusterIP
  ports:
    - port: 5432

#  ports:
#    - name: tcp
#      protocol: TCP
#      port: 5432
#      targetPort: 5432