appConfig:
  springApplicationUserServiceUrl: http://user-service-svc:8091/api/users
  springDatasourceUrl: jdbc:postgresql://postgresql:5432/post_db
  springDatasourceUsername: epam_post
appSecrets:
  springDatasourcePassword: "post_password"
kubernetesClusterDomain: cluster.local
serviceApp:
  containerPort: 8081
  image:
    repository: epamshorasulshoazimov/post-service
    pullPolicy: Always
    tag: 1.0.2
  replicas: 3
serviceSvc:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP

fullnameOverride: "post-ms"
nameOverride: "post-ms"