apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: epamshorasulshoazimov/user-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pg-user-db-svc:5432/user_db
            - name: SPRING_DATASOURCE_USERNAME
              value: epam_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: epam
            - name: SPRING_APPLICATION_USER_SERVICE_URL
              value: http://post-service-svc:8091/api/users


---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  type: NodePort
  ports:
    - port: 8091
      targetPort: 8091
      nodePort: 30091
  selector:
    app: user-service-app