apiVersion: v1
kind: ConfigMap
metadata:
  name: post-app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/post_db
  SPRING_DATASOURCE_USERNAME: epam_post
  SPRING_APPLICATION_USER_SERVICE_URL: http://user-service-svc:8091/api/users