apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-service-app
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: post-service-app
    spec:
      containers:
        - name: post-service-app
          image: epamshorasulshoazimov/post-service:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: post-app-secrets
            - configMapRef:
                name: post-app-config

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 2
            periodSeconds: 30
            terminationGracePeriodSeconds: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1