apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: post-service-app
    spec:
      containers:
        - name: post-service-app
          image: epamshorasulshoazimov/post-service:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: post-app-secrets
            - configMapRef:
                name: post-app-config

          livenessProbe:
            httpGet:
              path: /version
              port: 8081
            failureThreshold: 2
            periodSeconds: 60
            terminationGracePeriodSeconds: 60

          readinessProbe:
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 2
            httpGet:
              path: /version
              port: 8081