server:
  port: 8091

spring:
  application:
    name: USER-SERVICE

  datasource:
    username: epam_user
    url: jdbc:postgresql://host.docker.internal:5432/user_db
    password: epam
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
info:
  app:
    version: '@project.version@'