server:
  port: 8091

spring:
  application:
    name: USER-SERVICE

  datasource:
    username: epam_user
    url: jdbc:postgresql://localhost:54321/user_db
    password: epam
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

