apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: epamshorasulshoazimov/user-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          envFrom:
            - secretRef:
                name: user-app-secrets
            - configMapRef:
                name: user-app-config