apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: user-service-app
          image: epamshorasulshoazimov/user-service:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          envFrom:
            - secretRef:
                name: user-app-secrets
            - configMapRef:
                name: user-app-config
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            failureThreshold: 1
            periodSeconds: 60
            terminationGracePeriodSeconds: 60

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            initialDelaySeconds: 5
            periodSeconds: 10
