apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epam-apis
  namespace: kong
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /user-ms
            backend:
              service:
                name: user-service-svc
                port:
                  number: 8091
          - pathType: Prefix
            path: /post-ms
            backend:
              service:
                name: post-service-svc
                port:
                  number: 8081