apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-app.fullname" . }}-app-secrets
  labels:
  {{- include "backend-app.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_PASSWORD: {{ required "appSecrets.springDatasourcePassword is required" .Values.appSecrets.springDatasourcePassword | b64enc | quote }}
type: Opaque