apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-app.fullname" . }}-app-config
  labels:
  {{- include "backend-app.labels" . | nindent 4 }}
data:
  SPRING_APPLICATION_USER_SERVICE_URL: {{ .Values.appConfig.springApplicationUserServiceUrl
    | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.appConfig.springDatasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.appConfig.springDatasourceUsername | quote
    }}